{
  "hash": "46ab905235f408637957d134607e0274",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 3: Preparing HDB data for Geographically Weighted Predictive Model\"\nauthor: \"Nguyen Bao Thu Phuong\"\ndate: \"8 November 2024\" \ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  message: false\n  freeze: true\n---\n\n\n# Overview\n\n## Setting the Scene\n\nHousing is a crucial part of household wealth globally and often represents a major investment. Housing prices are influenced by global factors, like a country's economy and inflation, as well as property-specific factors that can be divided into structural and locational categories. Structural factors relate to the property itself, such as size, fittings, and tenure, while locational factors pertain to neighborhood characteristics like proximity to childcare centers, public transportation, and shopping centers.\n\nTraditionally, predictive models for housing resale prices have used the Ordinary Least Square (OLS) method. However, this approach does not account for spatial autocorrelation and spatial heterogeneity present in geographic datasets like housing transactions, potentially leading to biased or inefficient predictions (Anselin 1998). To address these limitations, Geographically Weighted Models (GWM) were introduced, offering more accurate calibrations for housing price predictions.\n\n## Objective\n\nThis study will calibrate both non-spatial and spatially weighted predictive models to forecast Singapore HDB resale prices for July-September 2024, using 2023 HDB resale transaction records. We will compare the derived models and their performances to understand the differences between conventional and spatially weighted predictive models.\n\n## The Data\n\nFor this study, the HDB Resale Flat Prices dataset from [Data.gov.sg](https://data.gov.sg/datasets/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/view) will be used as the core dataset.\n\nThe below datasets are also included to derive the recommended predictors for calibrating the models:\n\n-   MRT (Train Station Exit Point shapefile, updated June 2024), Bus Stop (updated July 2024): [LTA DataMall](https://datamall.lta.gov.sg/content/datamall/en.html)\n\n-   Eldercare, Hawker Centres, Parks, Supermarkets, CHAS Clinics, Childcare Services, Kindergartens: Geojson/shapefile data from [Data.gov.sg](https://data.gov.sg/).\n\n-   Shopping mall: list from [Wikipedia](https://en.wikipedia.org/wiki/List_of_shopping_malls_in_Singapore)\n\n-   Primary school: csv list from [Data.gov.sg](https://data.gov.sg/) (General information of schools dataset)\n\n-   Top school by popularity in 2024: as of [Local salary forum](https://www.salary.sg/2024/best-primary-schools-2024-by-popularity/)\n\nThe recommended predictors include both structural and location related factors:\n\n-   Structural factors\n\n    -   Area of the unit\n\n    -   Floor level\n\n    -   Remaining lease\n\n    -   Age of the unit\n\n    -   Flat model\n\n-   Locational factors\n\n    -   Proxomity to CBD\n\n    -   Proximity to eldercare\n\n    -   Proximity to foodcourt/hawker centres\n\n    -   Proximity to MRT\n\n    -   Proximity to park\n\n    -   Proximity to good primary school\n\n    -   Proximity to shopping mall\n\n    -   Proximity to supermarket\n\n    -   Numbers of kindergartens within 350m\n\n    -   Numbers of childcare centres within 350m\n\n    -   Numbers of bus stop within 350m\n\n    -   Numbers of primary school within 1km\n\n# Import R Packages\n\nThe below code chunk uses `p_load()` of pacman package to install and load relevant packages into R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(rvest,jsonlite ,sf, SpatialML, tmap, Metrics, tidyverse, ggplot2, olsrr)\n```\n:::\n\n\n-   **rvest**: use for web crawling\n\n-   **jsonlite**: to convert json file to dataframe format\n\n-   **sf**: Simplifies handling and analysis of spatial vector data using simple features.\n\n-   **SpatialML**: Integrates spatial machine learning for predictive modeling with spatial data.\n\n-   **tmap**: Creates thematic maps for spatial data with interactive and static plotting.\n\n-   **Metrics**: Offers a suite of standard performance metrics for evaluating predictive models.\n\n-   **tidyverse**: A collection of packages for data manipulation, exploration, and visualization.\n\n-   **ggplot2**: Provides a flexible, grammar-based approach to create complex visualizations.\n\n-   **olsrr**: Provide tools for OLS regression.\n\n# Import Geospatial and Aspatial Data\n\n## Import Aspatial Data\n\n### HDB Resale Transactions\n\nFirst we load in the Resale transactions from January 2023 to December 2023 and from July 2024 to September 2024 in `resale.csv` into R environment using the below functions:\n\n-   `read_csv()`: to read in csv file\n\n-   `filter()`: to filter for the relevant months\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale_raw <- read_csv(\"data/rawdata/resale.csv\") %>%\n  filter(month >= \"2023-01\" & month <= \"2023-12\" | month >= \"2024-07\" & month <= \"2024-09\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 192234 Columns: 11\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (8): month, town, flat_type, block, street_name, storey_range, flat_mode...\ndbl (3): floor_area_sqm, lease_commence_date, resale_price\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\nAs flats with different number of rooms tend to have very different price range, we plot multiple box plots to visualize the price range of different room types using `ggplot` functions as in the below code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create box plot of resale_price by flat_type\nggplot(resale_raw, aes(x = flat_type, y = resale_price)) +\n  geom_boxplot() +\n  labs(\n    title = \"Box Plot of Resale Prices by Flat Type\",\n    x = \"Flat Type\",\n    y = \"Resale Price\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe box plots show that resale price range increase with flat size. The price range is especially wider for flat type with 3 ROOM, 4 ROOM and 5 ROOM, with 3 ROOM having the widest range.\n\nNext we plot the number of transactions for each flat type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a column chart for the number of transactions by flat_type\nggplot(resale_raw, aes(x = flat_type)) +\n  geom_bar(fill = \"skyblue\", color = \"black\") +\n  labs(\n    title = \"Number of Transactions by Flat Type\",\n    x = \"Flat Type\",\n    y = \"Number of Transactions\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe column chart indicates that 4-room flats had the highest transaction volume during the selected period, nearing 15,000 transactions, while both 3-room and 5-room flats recorded over 7,500 transactions each. Given that each flat type has a distinct price range, this study will focus on 3-room flats due to their higher price variability. This variability poses a challenge for prediction, offering a way to distinguish model performance. This flat type also has sufficient number of records to calibrate predictive models.\n\nThe below code create additional attributes and filter for `flat_type = 3 ROOM` using the below functions. The output is saved in `resale_tidy` tibble dataframe.\n\n-   `filter()`: filter for flat_type == 3 ROOM\n\n-   `mutate()`: create new columns on:\n\n    -   `address`: using paste() to concatenate block and street name\n\n    -   `remaining_lease_yr`: extract the number of years as integer from remaining_lease column\n\n    -   `remaining_lease_mth`: extract the number of months as integer from remaining_lease column. Return 0 if the number of months is not provided.\n\n    -   `remaining_lease_yrs`: total remaining lease in years (= remaining_lease_yr + remaining_lease_mth/12)\n\n    -   `storey_order`: extract the first number from storey_range\n\n    -   `unit_age`: = current year - lease commencement date\n\n-   `select()`: to select relevant columns\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurrent_year = 2024\n\nresale_tidy <- resale_raw %>%\n  filter(flat_type == \"3 ROOM\") |>\n  mutate(address = paste(block,street_name)) %>%\n  mutate(remaining_lease_yr = as.integer(\n    str_sub(remaining_lease, 0, 2)))%>%\n   mutate(remaining_lease_mth = if_else(\n    is.na(as.integer(str_sub(remaining_lease, 9, 11))),0,\n    as.integer(str_sub(remaining_lease, 9, 11)) # to handle cases where there are no month value\n  )) |>\n  mutate(remaining_lease_yrs = remaining_lease_yr + remaining_lease_mth/12) |>\n  mutate(storey_order = as.integer(\n    str_sub(storey_range, 0, 2))) |>\n  mutate(unit_age = 2024 - lease_commence_date ) |>\n  select(c(\"address\",\"month\",\"flat_model\",\"floor_area_sqm\",\"resale_price\",\"remaining_lease_yrs\",\"storey_order\",\"unit_age\"))\n```\n:::\n\n\nNext we use summary() of base R to have an overview of `resale_tidy`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(resale_tidy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   address             month            flat_model        floor_area_sqm  \n Length:8264        Length:8264        Length:8264        Min.   : 52.00  \n Class :character   Class :character   Class :character   1st Qu.: 66.00  \n Mode  :character   Mode  :character   Mode  :character   Median : 67.00  \n                                                          Mean   : 68.13  \n                                                          3rd Qu.: 69.00  \n                                                          Max.   :366.70  \n  resale_price     remaining_lease_yrs  storey_order       unit_age    \n Min.   : 150000   Min.   :41.42       Min.   : 1.000   Min.   : 4.00  \n 1st Qu.: 362000   1st Qu.:53.50       1st Qu.: 4.000   1st Qu.:13.00  \n Median : 400000   Median :59.58       Median : 7.000   Median :40.00  \n Mean   : 419939   Mean   :65.14       Mean   : 7.078   Mean   :34.64  \n 3rd Qu.: 450000   3rd Qu.:86.44       3rd Qu.:10.000   3rd Qu.:46.00  \n Max.   :1568000   Max.   :95.50       Max.   :40.000   Max.   :58.00  \n```\n\n\n:::\n:::\n\n\nThe output shows this dataframe contains 8264 records, with no column having records with NA values. NA values can cause issue when running predictive modelling later. We proceed with this dataset for further analysis.\n\nNext we extract the list of unique addresses from `resale_tidy` to scrape for the respective coordinates from OneMap API. The list is sorted to ensure the first address is always picked up and hence the scraping process is optimal. The output is saved in `add_list`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadd_list <- sort(unique(resale_tidy$address))\n```\n:::\n\n\nThe below `get_coords` function reads in any address list and return the respective postal code, longitude and latitude in a dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nget_coords <- function(add_list){\n  \n  # Create a data frame to store all retrieved coordinates\n  postal_coords <- data.frame()\n    \n  for (i in add_list){\n    #print(i)\n    # as the API provided code for 1 address search at a time only, for pasrsing a list of addresses we use the common/elastic/search syntax as below\n    r <- GET('https://www.onemap.gov.sg/api/common/elastic/search?',\n           query=list(searchVal=i,\n                     returnGeom='Y',\n                     getAddrDetails='Y'))\n    data <- fromJSON(rawToChar(r$content))\n    found <- data$found\n    res <- data$results\n    \n    # Create a new data frame for each address\n    new_row <- data.frame()\n    \n    # If single result, append \n    if (found == 1){\n      postal <- res$POSTAL \n      lat <- res$LATITUDE\n      lng <- res$LONGITUDE\n      new_row <- data.frame(address= i, \n                            postal = postal, \n                            latitude = lat, \n                            longitude = lng)\n    }\n    \n    # If multiple results, drop NIL and append top 1\n    else if (found > 1){\n      # Remove those with NIL as postal\n      res_sub <- res[res$POSTAL != \"NIL\", ]\n      \n      # Set as NA first if no Postal\n      if (nrow(res_sub) == 0) {\n          new_row <- data.frame(address= i, \n                                postal = NA, \n                                latitude = NA, \n                                longitude = NA)\n      }\n      \n      else{\n        top1 <- head(res_sub, n = 1)\n        postal <- top1$POSTAL \n        lat <- top1$LATITUDE\n        lng <- top1$LONGITUDE\n        new_row <- data.frame(address= i, \n                              postal = postal, \n                              latitude = lat, \n                              longitude = lng)\n      }\n    }\n\n    else {\n      new_row <- data.frame(address= i, \n                            postal = NA, \n                            latitude = NA, \n                            longitude = NA)\n    }\n    \n    # Add the row\n    postal_coords <- rbind(postal_coords, new_row)\n  }\n  return(postal_coords)\n}\n```\n:::\n\n\nWe run the `get_coords()` function on `add_list` to retrieve the addresses' coordinates from OneMap API. The result is saved in `coords` dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- get_coords(add_list)\n```\n:::\n\n\nWe write the result coordinates to rds file format using below code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(coords, \"data/rds/coords.rds\")\n```\n:::\n\n\nThe below code chunk read the HDB block coordinates from rds file into `block_coords` dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblock_coords = read_rds(\"data/rds/coords.rds\")\n```\n:::\n\n\nNext we convert `resale_tidy` into an **sf** dataframe `resale` using the below functions:\n\n-   `left_join()`: join `resale_tidy` tibble data frame with `block_coords` on the `address` column\n\n-   `st_as_sf()`: convert into an **sf** dataframe using CRS *4326* as the obtained longitude and latitude is in WGS84 coordinates system.\n\n-   `st_transform()`: reproject the coordinates to Singapore projected CRS SVY21\n\n-   `select()`: exclude column `postal` since it is not needed in the remaining steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale <- resale_tidy |>\n  left_join(block_coords, by = \"address\") |>\n  st_as_sf(coords = c(\"longitude\", \"latitude\"),\n           crs=4326) |>\n  st_transform(crs = 3414) |>\n  select(-c(\"postal\"))\n```\n:::\n\n\nThe code chunk below converts `block_coords` to an sf data frame called `hdb_coords` to derive other geospatial attributes of HDB block (proximity to other amenities, number of amenities within close distance to the block). The below functions are used:\n\n-   `st_as_sf()`: convert into an **sf** dataframe using CRS *4326* as the obtained longitude and latitude is in WGS84 coordinates system.\n\n-   `st_transform()`: reproject the coordinates to Singapore projected CRS SVY21\n\n-   `select()`: exclude column `postal` since it is not needed in the remaining steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_coords = block_coords |>\n  st_as_sf(coords = c(\"longitude\", \"latitude\"),\n           crs=4326) |>\n  st_transform(crs = 3414) |>\n  select(-c(\"postal\"))\n```\n:::\n\n\n## Import Geospatial Data\n\n::: panel-tabset\n### Singapore Master Plan Subzone Boundary\n\nThe below code chunk imports Singapore Planning Subzone boundary to `mpsz` sf dataframe using the below functions:\n\n-   `st_read()`: to read in shapefile\n\n-   `st_transform()`: to ensure the coordinates are transforms to the correct CRS *3414* of Singapore Projected Coordinate System SVY21.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = st_read(dsn = \"data/rawdata\",\n               layer = \"MP14_SUBZONE_WEB_PL\") |>\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n### Eldercare\n\nThe below code chunks read in the eldercare shapefile as downloaded from Data.gov.sg using `st_read()`. After that `st_transform()` is used to reproject the coordinates to CRS *3414* of Singapore Projected CRS SVY21.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neldercare = st_read(dsn = 'data/rawdata',\n                    layer = 'ELDERCARE') |>\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ELDERCARE' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata' \n  using driver `ESRI Shapefile'\nSimple feature collection with 133 features and 18 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 14481.92 ymin: 28218.43 xmax: 41665.14 ymax: 46804.9\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n### CHAS Clinic\n\nThe below code chunks read in the CHAS clinics shapefile as downloaded from Data.gov.sg using `st_read()`. After that `st_transform()` is used to reproject the coordinates to CRS *3414* of Singapore Projected CRS SVY21. As the POINT features are given in 3 dimension XYZ, we use `st_zm()` to drop dimension Z as it is not required in the remaining steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCHAS = st_read('data/rawdata/CHASClinics.kml') |>\n  st_transform(crs = 3414) |>\n  st_zm(drop = TRUE, what = \"ZM\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MOH_CHAS_CLINICS' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata\\CHASClinics.kml' \n  using driver `KML'\nSimple feature collection with 1193 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.5818 ymin: 1.016264 xmax: 103.9903 ymax: 1.456037\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### Hawker\n\nThe below code chunks read in the Hawker geojson file as downloaded from Data.gov.sg using `st_read()`. After that `st_transform()` is used to reproject the coordinates to CRS *3414* of Singapore Projected CRS SVY21. As the POINT features are given in 3 dimension XYZ, we use `st_zm()` to drop dimension Z as it is not required in the remaining steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhawker = st_read('data/rawdata/HawkerCentresGEOJSON.geojson') |>\n  st_transform(crs = 3414) |>\n  st_zm(drop = TRUE, what = \"ZM\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `HawkerCentresGEOJSON' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata\\HawkerCentresGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 125 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6974 ymin: 1.272716 xmax: 103.9882 ymax: 1.449017\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### Parks\n\nThe below code chunks read in the Parks geojson file as downloaded from Data.gov.sg using `st_read()`. After that `st_transform()` is used to reproject the coordinates to CRS *3414* of Singapore Projected CRS SVY21. As the POINT features are given in 3 dimension XYZ, we use `st_zm()` to drop dimension Z as it is not required in the remaining steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparks = st_read('data/rawdata/Parks.geojson') |>\n  st_transform(crs = 3414)|>\n  st_zm(drop = TRUE, what = \"ZM\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Parks' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata\\Parks.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 430 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6929 ymin: 1.214491 xmax: 104.0538 ymax: 1.462094\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### Supermarkets\n\nThe below code chunks read in the Supermarketss geojson file as downloaded from Data.gov.sg using `st_read()`. After that `st_transform()` is used to reproject the coordinates to CRS *3414* of Singapore Projected CRS SVY21. As the POINT features are given in 3 dimension XYZ, we use `st_zm()` to drop dimension Z as it is not required in the remaining steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupermarkets = st_read('data/rawdata/SupermarketsGEOJSON.geojson') |>\n  st_transform(crs = 3414)|>\n  st_zm(drop = TRUE, what = \"ZM\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SupermarketsGEOJSON' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata\\SupermarketsGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 526 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6258 ymin: 1.24715 xmax: 104.0036 ymax: 1.461526\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### Childcare Services\n\nThe below code chunks read in the Childcare Services centres geojson file as downloaded from Data.gov.sg using `st_read()`. After that `st_transform()` is used to reproject the coordinates to CRS *3414* of Singapore Projected CRS SVY21. As the POINT features are given in 3 dimension XYZ, we use `st_zm()` to drop dimension Z as it is not required in the remaining steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcare = st_read('data/rawdata/ChildCareServices.geojson') |>\n  st_transform(crs = 3414)|>\n  st_zm(drop = TRUE, what = \"ZM\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ChildCareServices' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata\\ChildCareServices.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1925 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### Kindergarten\n\nThe below code chunks read in the Kindergarten geojson file as downloaded from Data.gov.sg using `st_read()`. After that `st_transform()` is used to reproject the coordinates to CRS *3414* of Singapore Projected CRS SVY21. As the POINT features are given in 3 dimension XYZ, we use `st_zm()` to drop dimension Z as it is not required in the remaining steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkindergarten = st_read('data/rawdata/Kindergartens.geojson') |>\n  st_transform(crs = 3414)|>\n  st_zm(drop = TRUE, what = \"ZM\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Kindergartens' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata\\Kindergartens.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 448 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6887 ymin: 1.247759 xmax: 103.9717 ymax: 1.455452\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### Bus Stops\n\nThe below code chunks read in the Bus stop shapefile as downloaded from LTA DataMall using `st_read()`. After that `st_transform()` is used to reproject the coordinates to CRS *3414* of Singapore Projected CRS SVY21.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbus_stop = st_read(dsn = 'data/rawdata',\n              layer = 'BusStop') |>\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `BusStop' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5166 features and 3 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 3970.122 ymin: 26482.1 xmax: 48285.52 ymax: 52983.82\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\nWe check for duplicated records using the below code chunk. The output shows this dataset does not contain any duplicated records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbus_duplicate <- bus_stop %>% \n  group_by_all() %>% \n  filter(n()>1) %>% \n  ungroup()\n  \nbus_duplicate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 0 features and 3 fields\nBounding box:  xmin: NA ymin: NA xmax: NA ymax: NA\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 0 × 4\n# ℹ 4 variables: BUS_STOP_N <chr>, BUS_ROOF_N <chr>, LOC_DESC <chr>,\n#   geometry <GEOMETRY [m]>\n```\n\n\n:::\n:::\n\n\n### MRT Exit\n\nThe below code chunks read in the MRT Station Exit shapefile as downloaded from LTA DataMall using `st_read()`. After that `st_transform()` is used to reproject the coordinates to CRS *3414* of Singapore Projected CRS SVY21.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMRT_exit = st_read(dsn = 'data/rawdata',\n              layer = 'Train_Station_Exit_Layer') |>\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Train_Station_Exit_Layer' from data source \n  `C:\\thuphuong1110\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\rawdata' \n  using driver `ESRI Shapefile'\nSimple feature collection with 593 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 6134.086 ymin: 27499.7 xmax: 45356.36 ymax: 47865.92\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\nWe check for duplicated records using the below code chunk. The output shows this dataset does not contain any duplicated records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexit_duplicate <- MRT_exit %>% \n  group_by_all() %>% \n  filter(n()>1) %>% \n  ungroup()\n  \nexit_duplicate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 0 features and 2 fields\nBounding box:  xmin: NA ymin: NA xmax: NA ymax: NA\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 0 × 3\n# ℹ 3 variables: stn_name <chr>, exit_code <chr>, geometry <GEOMETRY [m]>\n```\n\n\n:::\n:::\n\n\n### Shopping mall\n\nAs shopping mall coordinates dataset is not readily available, first we took the shopping mall name list from Wikipedia and saved in `shopping_mall.csv`. The below code chunk use `read_csv()` to read this list into `shopping_mall` dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshopping_mall = read_csv(\"data/rawdata/shopping_mall.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 174 Columns: 1\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): shopping_mall\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\nNext we create a list of unique shopping mall name using `unique()` function and save the output in `mall_list`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmall_list = unique(shopping_mall$shopping_mall)\n```\n:::\n\n\nThe below code chunk uses the previously defined `get_coords()` function to retrieve the respective coordinates for the shopping malls in `mall_list` from OneMap API. The output is saved in `mall_coords_full`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmall_coords_full <- get_coords(mall_list)\n```\n:::\n\n\nThe code chunk below converts `mall_coords_full` from a tibble dataframe to an sf data frame called `mall_coords` to facilitate future distance calculation. The below functions are used:\n\n-   `st_as_sf()`: convert into an **sf** dataframe using CRS *4326* as the obtained longitude and latitude is in WGS84 coordinates system.\n\n-   `st_transform()`: reproject the coordinates to Singapore projected CRS SVY21.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmall_coords = mall_coords_full |>\n    st_as_sf(coords = c(\"longitude\", \"latitude\"),\n           crs=4326) |>\n  st_transform(crs = 3414)\n```\n:::\n\n\nThe below code chunk writes the result to rds file for future usage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mall_coords, \"data/rds/mall_coords.rds\")\n```\n:::\n\n\nWe read the output from rds file into `mall_coords` using below code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmall_coords = read_rds(\"data/rds/mall_coords.rds\")\n```\n:::\n\n\n### Primary School\n\nAs primary school coordinates dataset is not readily available, first we read in the school information of all schools provided by MOE using `read_csv()` and perform the below steps. The output is save in `primary_school` dataframe.\n\n-   `filter()`: filter for Primary school only\n\n-   `select()`: select relevant columns\n\n-   `toupper()`: upper case all school name for joining with the top schools list later on, as `left_join()` is case sensitive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_school = read_csv(\"data/rawdata/school_information.csv\") |>\n  filter(mainlevel_code == \"PRIMARY\") |>\n  select(c(\"school_name\",\"address\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 338 Columns: 31\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (29): school_name, url_address, address, telephone_no, telephone_no_2, f...\ndbl  (1): postal_code\nlgl  (1): sixth_vp_name\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nprimary_school$school_name <- toupper(primary_school$school_name) # upper case all school name\n```\n:::\n\n\nThe below code chunk obtains a list of unique school address and save in `school_list`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool_list = unique(primary_school$address)\n```\n:::\n\n\nWe run the function `get_coords` again to scrape the coordinates from OneMap API for the school addresses in `school_list`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool_coords <- get_coords(school_list)\n```\n:::\n\n\nThe code chunk below converts `school_coords` from a tibble dataframe to an sf data frame to facilitate future distance calculation. The below functions are used:\n\n-   `st_as_sf()`: convert into an **sf** dataframe using CRS *4326* as the obtained longitude and latitude is in WGS84 coordinates system.\n\n-   `st_transform()`: reproject the coordinates to Singapore projected CRS SVY21.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool_coords = school_coords |>\n    st_as_sf(coords = c(\"longitude\", \"latitude\"),\n           crs=4326) |>\n  st_transform(crs = 3414)\n```\n:::\n\n\nThe below code chunk writes the result to rds file for future usage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(school_coords, \"data/rds/school_coords.rds\")\n```\n:::\n\n\nWe read the output from rds file into `school_coords` using the below code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool_coords = read_rds(\"data/rds/school_coords.rds\")\n```\n:::\n\n\nNext we left join `school_coords` with `primary_school` with `school_coords` on the left side to ensure the output is an **sf** dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_school = school_coords |>\n  left_join(primary_school, by = \"address\")\n```\n:::\n\n\nThe below code chunk reads in primary school subscription rate as obtained from Local Salary Forum using `read_csv()`, followed by `toupper()` to convert the school names to upper case.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool_rate = read_csv(\"data/rawdata/school_rating.csv\") |>\n  select(c(\"school_name\",\"school_rating\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 180 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): list, school_name\ndbl (1): school_rating\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nschool_rate$school_name <- toupper(school_rate$school_name)\n```\n:::\n\n\nWe define top schools as popular schools which are oversubscribed in 2024 (subscription rate \\> 1). The below code chunk left join `primary_school` with `school_rate` and filter for top schools with subscription rate \\> 1. The result is saved in `top_school` sf dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_school = primary_school |>\n  left_join(school_rate, by = \"school_name\") |>\n  filter(school_rating > 1)\n\nsummary(top_school)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   address             postal          school_name        school_rating  \n Length:32          Length:32          Length:32          Min.   :1.010  \n Class :character   Class :character   Class :character   1st Qu.:1.177  \n Mode  :character   Mode  :character   Mode  :character   Median :1.415  \n                                                          Mean   :1.429  \n                                                          3rd Qu.:1.583  \n                                                          Max.   :2.130  \n          geometry \n POINT        :32  \n epsg:3414    : 0  \n +proj=tmer...: 0  \n                   \n                   \n                   \n```\n\n\n:::\n:::\n\n\nThe output returns 32 top schools by popularity, with min subscription rate of 1.01 and max subscription rate of 2.13.\n:::\n\n# Data Wrangling\n\n## Flat Models Dummy Columns\n\nWe plot the price range by each flat model using the below code chunks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create box plot of resale_price by flat_type\nggplot(resale, aes(x = flat_model, y = resale_price)) +\n  geom_boxplot() +\n  labs(\n    title = \"Box Plot of Resale Prices by Flat Model\",\n    x = \"Flat Model\",\n    y = \"Resale Price\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nThe box plots show clear differences in the price range of different flat models:\n\n-   **Terrace Model**: This model has the highest resale prices, with a significantly higher median and larger range than all other models. This suggests that Terrace units may be premium properties with unique characteristics.\n\n-   **DBSS, Model A and Premium Apartment Models**: these models also have relatively high resale prices, though their price ranges are narrower than Terrace, indicating more consistency in pricing for these models.\n\n-   **Standard, Simplified, New Generation and Improved Models**: These models have lower median resale prices and narrower ranges, which may imply they are more basic or standard options with less variability in resale price.\n\nNext we plot the number of transactions for each flat models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a column chart for the number of transactions by flat_model\nggplot(resale, aes(x = flat_model)) +\n  geom_bar(fill = \"skyblue\", color = \"black\") +\n  labs(\n    title = \"Number of Transactions by Flat Model\",\n    x = \"Flat Model\",\n    y = \"Number of Transactions\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nThe column chart shows Improved, Model A and New Generation models have the highest number of transactions (account for 87.3% of total number of transactions).\n\nThe below code chunk uses `model.matrix()` function to create dummy columns for each flat model, then `select()` is used to exclude the original flat_model columns and flat_modelTerrace as it will have multicollinearity with the remaining dummy columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using model.matrix to create dummy variables\nresale <- cbind(resale, model.matrix(~ flat_model - 1, data = resale))\n\n# Exclude the original flat_model columns and flat_modelTerrace to avoid multicollinearity\nresale = resale |>\n  select(-c(\"flat_model\",\"flat_modelTerrace\"))\n```\n:::\n\n\n## Proximity to Amenities\n\nProximity to amenities can significantly impact HDB resale prices in Singapore. Flats located near amenities like MRT stations, schools, shopping centers, and healthcare facilities tend to command higher resale values due to enhanced convenience and lifestyle appeal.\n\nAfter loading in the coordinates of all relevant amenities, in this section, we continue to calculate the distance of each HDB block to its nearest amenities.\n\nTo calculate the distance to CBD, first we create a simple feature geometry list column given CBD longitude and latitude as look up from Google using below code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbd_coords <- st_sfc(st_point(c(103.851784, 1.287953)), crs = 4326) |>\n  st_transform(crs = 3414)\n```\n:::\n\n\nThe below code chunk calculates the proximity of each HDB block to its relevant amenities, including proximity to CBD, nearest Eldercare, MRT exit, CHAS clinic, Hawker, Shopping Mall, Park, Top School, Supermarkets. `select()` is used at the end to select for relevant columns only.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate distance from each block to different amenities in kilometers\nhdb_coords <- hdb_coords %>%\n  mutate(\n    PROX_CBD = as.numeric(st_distance(geometry, cbd_coords, by_element = FALSE)) / 1000,\nnearest_eldercare = st_nearest_feature(geometry, eldercare),\nPROX_ELDERCARE = as.numeric(st_distance(geometry,\n                                        eldercare[nearest_eldercare, ],\n                                        by_element = TRUE)) / 1000,\nnearest_MRT_exit = st_nearest_feature(geometry, MRT_exit),\n    PROX_MRT = as.numeric(st_distance(geometry, MRT_exit[nearest_MRT_exit, ], by_element = TRUE)) / 1000,\nnearest_clinic = st_nearest_feature(geometry, CHAS),\n    PROX_CLINIC = as.numeric(st_distance(geometry, CHAS[nearest_clinic, ], by_element = TRUE)) / 1000,\nnearest_hawker = st_nearest_feature(geometry, hawker),\n    PROX_HAWKER = as.numeric(st_distance(geometry, hawker[nearest_hawker, ], by_element = TRUE)) / 1000,\nnearest_park = st_nearest_feature(geometry, parks),\n    PROX_PARK = as.numeric(st_distance(geometry, parks[nearest_park, ], by_element = TRUE)) / 1000,\nnearest_top_school = st_nearest_feature(geometry, top_school),\n    PROX_TOP_SCHOOL = as.numeric(st_distance(geometry, top_school[nearest_top_school, ], by_element = TRUE)) / 1000,\nnearest_mall = st_nearest_feature(geometry, mall_coords),\n    PROX_MALL = as.numeric(st_distance(geometry, mall_coords[nearest_mall, ], by_element = TRUE)) / 1000,\nnearest_supermarket = st_nearest_feature(geometry, supermarkets),\n    PROX_SUPERMARKETS = as.numeric(st_distance(geometry, supermarkets[nearest_supermarket, ], by_element = TRUE)) / 1000\n) |>\n  select(c(\"address\",\"PROX_MRT\",\"PROX_CBD\",\"PROX_ELDERCARE\",\n           \"PROX_CLINIC\",\"PROX_HAWKER\",\"PROX_PARK\",\"PROX_TOP_SCHOOL\",\n           \"PROX_MALL\",\"PROX_SUPERMARKETS\"))\n```\n:::\n\n\n## Number of amenities within close distance\n\nIn this section, we count the number of important amenities that is within a defined distance to each HDB block.\n\n### Distance 350m\n\nThe below code chunks create a buffer of 350m around each HDB block using `st_buffer()`. The output is saved in `buffer_350m` sf dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_350m = st_buffer(hdb_coords, dist = 350) |>\n  select(c(\"address\"))\n```\n:::\n\n\nWe plot the map using multiple **tmap** functions to see if the buffer area is properly created\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_options(check.and.fix = TRUE)\ntm_shape(mpsz) +\n  tm_polygons() +\n  tm_shape(buffer_350m) + \n  tm_polygons() +\n  tm_shape(eldercare) +\n  tm_dots()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The shape mpsz is invalid. See sf::st_is_valid\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nTo count the number of points with in a buffer area, first `st_intersects()` is used to identify the amenities that lie within the buffer area, then `lengths()` is used to count the number of points.\n\nThe below code chunk counts the number of kindergarten, childcare and bus stops that are within 350m distance from each HDB block. The results are saved in columns `kindergarten_count`, `childcare_count` and `bus_stop_count` of `buffer_350m` sf dataframe respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_350m$kindergarten_count = lengths(\n  st_intersects(buffer_350m, kindergarten))\n\nbuffer_350m$childcare_count = lengths(\n  st_intersects(buffer_350m, childcare))\n\nbuffer_350m$bus_stop_count = lengths(\n  st_intersects(buffer_350m, bus_stop))\n```\n:::\n\n\n### Distance 1km\n\nThe below code chunks create a buffer of 1km around each HDB block using `st_buffer()`. The output is saved in `buffer_1km` sf dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_1km = st_buffer(hdb_coords, dist = 1000) |>\n  select(c(\"address\"))\n```\n:::\n\n\nSimilar to the previous section, the below code chunk counts the number of primary schools that are within 1km distance from each HDB block. The results are saved in columns `pri_school_count` of `buffer_1km` sf dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_1km$pri_school_count = lengths(\n  st_intersects(buffer_1km, primary_school))\n```\n:::\n\n\n## Merge to final data frame\n\nIn this part, we merge all the previously derived proximity to amenities and count of amenities within close distance to `resale` sf dataframe to calibrate predictive models.\n\nFirst we need to drop geometry from `hdb_coords` sf dataframe to allow for joining with `resale` sf dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_coords_nogeo = st_drop_geometry(hdb_coords)\n```\n:::\n\n\nThe below code chunk join `resale` with `hdb_coords_nogeo` to bring in proximity to amenities for each transaction using `left_join()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale <- resale |>\n  left_join(hdb_coords_nogeo, by = \"address\")\n```\n:::\n\n\nSimilarly, we need to drop geometry from `buffer_350m` sf dataframe to allow for joining with `resale` sf dataframe. The below code chunk uses `st_drop_geometry()` and `left_join()` to perform these operations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove geometry\nbuffer_350m_nogeo = st_drop_geometry(buffer_350m)\n# Perform left_join\nresale = resale |>\n  left_join(buffer_350m_nogeo, by = \"address\")\n```\n:::\n\n\nThe same steps are performed to join `resale` with `buffer_1km_nogeo` to bring in the count of primary schools within 1 kilometer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove geometry\nbuffer_1km_nogeo = st_drop_geometry(buffer_1km)\n# Perform left_join\nresale = resale |>\n  left_join(buffer_1km_nogeo, by = \"address\")\n```\n:::\n\n\n# Compute Correlation Matrix\n\nBefore loading the predictors into a predictive model, It is a good practice to use correlation matrix to examine if there is sign of multicollinearity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale_nogeo <- resale %>%\n  st_drop_geometry() |>\n  select(-c(\"address\",\"month\",\"resale_price\"))\ncorrplot::corrplot(cor(resale_nogeo), \n                   diag = FALSE, \n                   order = \"AOE\",\n                   tl.pos = \"td\", \n                   tl.cex = 0.5, \n                   method = \"number\", \n                   type = \"upper\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-55-1.png){width=960}\n:::\n:::\n\n\nThe correlation matrix shows that `unit_age` and `remaining_lease_yrs` have perfect correlation, hence we will exclude `unit_age`. `flat_modelModel.A` also has quite strong correlation with `remaining_lease_yrs` , but the value is below 0.8, so we still use both of these variables when calibrating the predictive models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale = resale |>\n  select(-c(\"unit_age\"))\n```\n:::\n\n\n# Derive train and test dataset.\n\n## Check for Overlapping Points\n\nWhen using the GWmodel package to calibrate explanatory or predictive models, it is essential to ensure there are no overlapping point features. The code chunk below checks if there is any overlapping points presented in the `resale` sf dataframe that we used to split into `train_data` and `test_data`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverlapping_points <- resale %>%\n  mutate(overlap = lengths(st_equals(., .)) > 1)\n\nsum(overlapping_points$overlap == TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7706\n```\n\n\n:::\n:::\n\n\nThe output shows there are 7,706 overlapping points. This is expected to happen as flats in the same block will have the same postal code, which indicate same address and coordinates.\n\nWe use `st_jitter()` of **sf** package to move the point features by 5 meters to avoid overlapping cases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale = resale |>\n  st_jitter(amount = 5)\n```\n:::\n\n\nThe below code chunk creates training dataset using `filter()` to filter for transactions in 2023 only. The output is saved in `train_data` sf dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data = resale |>\n  filter(month >= \"2023-01\" & month <= \"2023-12\") |>\n  select(-c(\"address\",\"month\"))\n```\n:::\n\n\nNext we create testing dataset using `filter()` to filter for transactions from July 2024 to September 2024. The output is saved in `test_data` sf dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data = resale |>\n  filter(month >= \"2024-07\" & month <= \"2024-09\") |>\n  select(-c(\"address\",\"month\"))\n```\n:::\n\n\nThe below code chunk write the outputs to rds file for future usage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(train_data, \"data/rds/train_data.rds\")\nwrite_rds(test_data, \"data/rds/test_data.rds\")\nwrite_rds(resale, \"data/rds/resale_data.rds\")\n```\n:::\n\n\nThe below code chunk reads the output from rds file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data = read_rds(\"data/rds/train_data.rds\")\ntest_data = read_rds(\"data/rds/test_data.rds\")\nresale = read_rds(\"data/rds/resale_data.rds\")\n```\n:::\n\n\n# Non-spatial Multiple Linear Regression\n\nThe below code chunk uses `lm()` function to calibrate a conventional multiple linear regression with `resale_price` as the dependent variable. Then `ols_regress()` from **olsrr** package is used to return the model result in high quality summary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_mlr <- lm(resale_price ~ floor_area_sqm +\n                  storey_order + remaining_lease_yrs +\n                  PROX_CBD + PROX_ELDERCARE + PROX_HAWKER +\n                  PROX_MRT + PROX_PARK + PROX_MALL + \n                  PROX_SUPERMARKETS + PROX_TOP_SCHOOL +\n                  PROX_CLINIC + kindergarten_count +\n                  childcare_count + bus_stop_count +\n                  pri_school_count + flat_modelDBSS +\n                  flat_modelImproved + flat_modelModel.A +\n                  flat_modelNew.Generation + flat_modelPremium.Apartment +\n                  flat_modelSimplified + flat_modelStandard,\n                data=train_data)\n\nols_regress(price_mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              Model Summary                                \n--------------------------------------------------------------------------\nR                           0.889       RMSE                    40486.104 \nR-Squared                   0.790       MSE                1645338285.651 \nAdj. R-Squared              0.789       Coef. Var                   9.848 \nPred R-Squared              0.788       AIC                    152921.465 \nMAE                     30165.637       SBC                    153090.390 \n--------------------------------------------------------------------------\n RMSE: Root Mean Square Error \n MSE: Mean Square Error \n MAE: Mean Absolute Error \n AIC: Akaike Information Criteria \n SBC: Schwarz Bayesian Criteria \n\n                                     ANOVA                                      \n-------------------------------------------------------------------------------\n                    Sum of                                                     \n                   Squares          DF       Mean Square       F          Sig. \n-------------------------------------------------------------------------------\nRegression    3.918497e+13          23      1.703695e+12    1035.468    0.0000 \nResidual      1.041664e+13        6331    1645338285.651                       \nTotal         4.960161e+13        6354                                         \n-------------------------------------------------------------------------------\n\n                                                  Parameter Estimates                                                    \n------------------------------------------------------------------------------------------------------------------------\n                      model           Beta    Std. Error    Std. Beta       t        Sig           lower          upper \n------------------------------------------------------------------------------------------------------------------------\n                (Intercept)     378947.733     21367.060                  17.735    0.000     337061.058     420834.409 \n             floor_area_sqm       4349.411       117.348        0.279     37.064    0.000       4119.369       4579.452 \n               storey_order       3619.876       103.419        0.224     35.002    0.000       3417.141       3822.612 \n        remaining_lease_yrs       3567.945        63.180        0.676     56.472    0.000       3444.091       3691.800 \n                   PROX_CBD      -8552.639       164.976       -0.432    -51.842    0.000      -8876.047      -8229.231 \n             PROX_ELDERCARE      -4310.637      1057.455       -0.027     -4.076    0.000      -6383.606      -2237.668 \n                PROX_HAWKER     -11054.238      1473.057       -0.052     -7.504    0.000     -13941.928      -8166.549 \n                   PROX_MRT     -35739.721      1673.780       -0.137    -21.353    0.000     -39020.897     -32458.545 \n                  PROX_PARK     -12773.720      1591.309       -0.053     -8.027    0.000     -15893.224      -9654.216 \n                  PROX_MALL     -14322.814      1568.783       -0.059     -9.130    0.000     -17398.159     -11247.468 \n          PROX_SUPERMARKETS       8668.112      3290.294        0.019      2.634    0.008       2218.020      15118.204 \n            PROX_TOP_SCHOOL        220.426       429.132        0.003      0.514    0.608       -620.819       1061.670 \n                PROX_CLINIC      53507.363      4851.012        0.076     11.030    0.000      43997.737      63016.990 \n         kindergarten_count       8314.813       689.591        0.084     12.058    0.000       6962.982       9666.645 \n            childcare_count      -2446.759       314.409       -0.055     -7.782    0.000      -3063.107      -1830.411 \n             bus_stop_count        662.993       210.434        0.020      3.151    0.002        250.471       1075.514 \n           pri_school_count      -1031.911       430.528       -0.017     -2.397    0.017      -1875.892       -187.930 \n             flat_modelDBSS    -317211.228     17149.803       -0.333    -18.496    0.000    -350830.650    -283591.805 \n         flat_modelImproved    -412220.945     16324.320       -1.950    -25.252    0.000    -444222.141    -380219.748 \n          flat_modelModel.A    -388141.852     16085.363       -2.093    -24.130    0.000    -419674.612    -356609.091 \n   flat_modelNew.Generation    -395584.837     16136.064       -2.051    -24.516    0.000    -427216.989    -363952.684 \nflat_modelPremium.Apartment    -382141.147     16481.762       -0.669    -23.186    0.000    -414450.984    -349831.309 \n       flat_modelSimplified    -365627.942     16509.370       -0.827    -22.147    0.000    -397991.901    -333263.983 \n         flat_modelStandard    -417547.617     16665.504       -1.040    -25.055    0.000    -450217.650    -384877.584 \n------------------------------------------------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nTaking a significance level of 0.05, the model output shows that `PROX_TOP_SCHOOL` is not statistically significant (p-value = 0.608). We remove this variable and calibrate the model again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_mlr <- lm(resale_price ~ floor_area_sqm +\n                  storey_order + remaining_lease_yrs +\n                  PROX_CBD + PROX_ELDERCARE + PROX_HAWKER +\n                  PROX_MRT + PROX_PARK + PROX_MALL + \n                  PROX_SUPERMARKETS + \n                  PROX_CLINIC + kindergarten_count +\n                  childcare_count + bus_stop_count +\n                  pri_school_count + flat_modelDBSS +\n                  flat_modelImproved + flat_modelModel.A +\n                  flat_modelNew.Generation + flat_modelPremium.Apartment +\n                  flat_modelSimplified + flat_modelStandard,\n                data=train_data)\n\nols_regress(price_mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              Model Summary                                \n--------------------------------------------------------------------------\nR                           0.889       RMSE                    40486.947 \nR-Squared                   0.790       MSE                1645146998.541 \nAdj. R-Squared              0.789       Coef. Var                   9.848 \nPred R-Squared              0.788       AIC                    152919.729 \nMAE                     30159.974       SBC                    153081.897 \n--------------------------------------------------------------------------\n RMSE: Root Mean Square Error \n MSE: Mean Square Error \n MAE: Mean Absolute Error \n AIC: Akaike Information Criteria \n SBC: Schwarz Bayesian Criteria \n\n                                     ANOVA                                      \n-------------------------------------------------------------------------------\n                    Sum of                                                     \n                   Squares          DF       Mean Square       F          Sig. \n-------------------------------------------------------------------------------\nRegression    3.918454e+13          22      1.781115e+12    1082.648    0.0000 \nResidual      1.041707e+13        6332    1645146998.541                       \nTotal         4.960161e+13        6354                                         \n-------------------------------------------------------------------------------\n\n                                                  Parameter Estimates                                                    \n------------------------------------------------------------------------------------------------------------------------\n                      model           Beta    Std. Error    Std. Beta       t        Sig           lower          upper \n------------------------------------------------------------------------------------------------------------------------\n                (Intercept)     379244.985     21357.980                  17.757    0.000     337376.110     421113.860 \n             floor_area_sqm       4349.027       117.339        0.279     37.064    0.000       4119.004       4579.051 \n               storey_order       3620.139       103.411        0.224     35.007    0.000       3417.418       3822.860 \n        remaining_lease_yrs       3570.120        63.035        0.676     56.637    0.000       3446.551       3693.689 \n                   PROX_CBD      -8541.687       163.582       -0.432    -52.216    0.000      -8862.364      -8221.010 \n             PROX_ELDERCARE      -4335.074      1056.323       -0.027     -4.104    0.000      -6405.824      -2264.324 \n                PROX_HAWKER     -11107.183      1469.360       -0.052     -7.559    0.000     -13987.628      -8226.739 \n                   PROX_MRT     -35761.228      1673.159       -0.138    -21.373    0.000     -39041.186     -32481.269 \n                  PROX_PARK     -12805.785      1589.991       -0.053     -8.054    0.000     -15922.706      -9688.864 \n                  PROX_MALL     -14308.595      1568.447       -0.059     -9.123    0.000     -17383.282     -11233.907 \n          PROX_SUPERMARKETS       8946.848      3245.049        0.020      2.757    0.006       2585.453      15308.243 \n                PROX_CLINIC      53354.486      4841.592        0.076     11.020    0.000      43863.326      62845.646 \n         kindergarten_count       8309.086       689.461        0.084     12.052    0.000       6957.510       9660.663 \n            childcare_count      -2449.677       314.339       -0.055     -7.793    0.000      -3065.888      -1833.465 \n             bus_stop_count        672.222       209.653        0.020      3.206    0.001        261.231       1083.213 \n           pri_school_count      -1087.880       416.487       -0.018     -2.612    0.009      -1904.335       -271.425 \n             flat_modelDBSS    -317473.800     17141.186       -0.333    -18.521    0.000    -351076.330    -283871.270 \n         flat_modelImproved    -412262.566     16323.170       -1.950    -25.256    0.000    -444261.507    -380263.625 \n          flat_modelModel.A    -388207.142     16083.926       -2.093    -24.136    0.000    -419737.084    -356677.199 \n   flat_modelNew.Generation    -395683.854     16133.975       -2.051    -24.525    0.000    -427311.910    -364055.799 \nflat_modelPremium.Apartment    -382073.977     16480.285       -0.669    -23.184    0.000    -414380.918    -349767.036 \n       flat_modelSimplified    -365721.163     16507.413       -0.828    -22.155    0.000    -398081.284    -333361.042 \n         flat_modelStandard    -417539.816     16664.528       -1.040    -25.056    0.000    -450207.936    -384871.697 \n------------------------------------------------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nAll the parameters have sifnigicant p-values now.\n\n## Multicollinearity check with VIF\n\nWe move on to examining the variance inflation factors of the independent variables using the `check_collinearity()` function of **performance** package as in below code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif <- performance::check_collinearity(price_mlr)\n\nkableExtra::kable(vif, \n      caption = \"Variance Inflation Factor (VIF) Results\") %>%\nkableExtra::kable_styling(font_size = 18) \n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"font-size: 18px; margin-left: auto; margin-right: auto;\">\n<caption style=\"font-size: initial !important;\">Variance Inflation Factor (VIF) Results</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Term </th>\n   <th style=\"text-align:right;\"> VIF </th>\n   <th style=\"text-align:right;\"> VIF_CI_low </th>\n   <th style=\"text-align:right;\"> VIF_CI_high </th>\n   <th style=\"text-align:right;\"> SE_factor </th>\n   <th style=\"text-align:right;\"> Tolerance </th>\n   <th style=\"text-align:right;\"> Tolerance_CI_low </th>\n   <th style=\"text-align:right;\"> Tolerance_CI_high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> floor_area_sqm </td>\n   <td style=\"text-align:right;\"> 1.707226 </td>\n   <td style=\"text-align:right;\"> 1.650506 </td>\n   <td style=\"text-align:right;\"> 1.768892 </td>\n   <td style=\"text-align:right;\"> 1.306609 </td>\n   <td style=\"text-align:right;\"> 0.5857455 </td>\n   <td style=\"text-align:right;\"> 0.5653257 </td>\n   <td style=\"text-align:right;\"> 0.6058748 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> storey_order </td>\n   <td style=\"text-align:right;\"> 1.235415 </td>\n   <td style=\"text-align:right;\"> 1.202017 </td>\n   <td style=\"text-align:right;\"> 1.274333 </td>\n   <td style=\"text-align:right;\"> 1.111492 </td>\n   <td style=\"text-align:right;\"> 0.8094449 </td>\n   <td style=\"text-align:right;\"> 0.7847244 </td>\n   <td style=\"text-align:right;\"> 0.8319347 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> remaining_lease_yrs </td>\n   <td style=\"text-align:right;\"> 4.298088 </td>\n   <td style=\"text-align:right;\"> 4.117224 </td>\n   <td style=\"text-align:right;\"> 4.489445 </td>\n   <td style=\"text-align:right;\"> 2.073183 </td>\n   <td style=\"text-align:right;\"> 0.2326616 </td>\n   <td style=\"text-align:right;\"> 0.2227447 </td>\n   <td style=\"text-align:right;\"> 0.2428821 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROX_CBD </td>\n   <td style=\"text-align:right;\"> 2.059046 </td>\n   <td style=\"text-align:right;\"> 1.985379 </td>\n   <td style=\"text-align:right;\"> 2.138220 </td>\n   <td style=\"text-align:right;\"> 1.434938 </td>\n   <td style=\"text-align:right;\"> 0.4856618 </td>\n   <td style=\"text-align:right;\"> 0.4676787 </td>\n   <td style=\"text-align:right;\"> 0.5036821 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROX_ELDERCARE </td>\n   <td style=\"text-align:right;\"> 1.303931 </td>\n   <td style=\"text-align:right;\"> 1.267001 </td>\n   <td style=\"text-align:right;\"> 1.345967 </td>\n   <td style=\"text-align:right;\"> 1.141898 </td>\n   <td style=\"text-align:right;\"> 0.7669121 </td>\n   <td style=\"text-align:right;\"> 0.7429603 </td>\n   <td style=\"text-align:right;\"> 0.7892650 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROX_HAWKER </td>\n   <td style=\"text-align:right;\"> 1.442244 </td>\n   <td style=\"text-align:right;\"> 1.398424 </td>\n   <td style=\"text-align:right;\"> 1.490884 </td>\n   <td style=\"text-align:right;\"> 1.200935 </td>\n   <td style=\"text-align:right;\"> 0.6933639 </td>\n   <td style=\"text-align:right;\"> 0.6707429 </td>\n   <td style=\"text-align:right;\"> 0.7150908 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROX_MRT </td>\n   <td style=\"text-align:right;\"> 1.247992 </td>\n   <td style=\"text-align:right;\"> 1.213937 </td>\n   <td style=\"text-align:right;\"> 1.287469 </td>\n   <td style=\"text-align:right;\"> 1.117136 </td>\n   <td style=\"text-align:right;\"> 0.8012870 </td>\n   <td style=\"text-align:right;\"> 0.7767176 </td>\n   <td style=\"text-align:right;\"> 0.8237663 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROX_PARK </td>\n   <td style=\"text-align:right;\"> 1.322621 </td>\n   <td style=\"text-align:right;\"> 1.284747 </td>\n   <td style=\"text-align:right;\"> 1.365532 </td>\n   <td style=\"text-align:right;\"> 1.150052 </td>\n   <td style=\"text-align:right;\"> 0.7560747 </td>\n   <td style=\"text-align:right;\"> 0.7323153 </td>\n   <td style=\"text-align:right;\"> 0.7783635 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROX_MALL </td>\n   <td style=\"text-align:right;\"> 1.256523 </td>\n   <td style=\"text-align:right;\"> 1.222024 </td>\n   <td style=\"text-align:right;\"> 1.296383 </td>\n   <td style=\"text-align:right;\"> 1.120947 </td>\n   <td style=\"text-align:right;\"> 0.7958469 </td>\n   <td style=\"text-align:right;\"> 0.7713769 </td>\n   <td style=\"text-align:right;\"> 0.8183147 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROX_SUPERMARKETS </td>\n   <td style=\"text-align:right;\"> 1.525103 </td>\n   <td style=\"text-align:right;\"> 1.477224 </td>\n   <td style=\"text-align:right;\"> 1.577786 </td>\n   <td style=\"text-align:right;\"> 1.234951 </td>\n   <td style=\"text-align:right;\"> 0.6556934 </td>\n   <td style=\"text-align:right;\"> 0.6337996 </td>\n   <td style=\"text-align:right;\"> 0.6769455 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROX_CLINIC </td>\n   <td style=\"text-align:right;\"> 1.419602 </td>\n   <td style=\"text-align:right;\"> 1.376897 </td>\n   <td style=\"text-align:right;\"> 1.467145 </td>\n   <td style=\"text-align:right;\"> 1.191471 </td>\n   <td style=\"text-align:right;\"> 0.7044228 </td>\n   <td style=\"text-align:right;\"> 0.6815958 </td>\n   <td style=\"text-align:right;\"> 0.7262706 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kindergarten_count </td>\n   <td style=\"text-align:right;\"> 1.450042 </td>\n   <td style=\"text-align:right;\"> 1.405838 </td>\n   <td style=\"text-align:right;\"> 1.499061 </td>\n   <td style=\"text-align:right;\"> 1.204177 </td>\n   <td style=\"text-align:right;\"> 0.6896351 </td>\n   <td style=\"text-align:right;\"> 0.6670843 </td>\n   <td style=\"text-align:right;\"> 0.7113193 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> childcare_count </td>\n   <td style=\"text-align:right;\"> 1.509137 </td>\n   <td style=\"text-align:right;\"> 1.462037 </td>\n   <td style=\"text-align:right;\"> 1.561038 </td>\n   <td style=\"text-align:right;\"> 1.228469 </td>\n   <td style=\"text-align:right;\"> 0.6626304 </td>\n   <td style=\"text-align:right;\"> 0.6405996 </td>\n   <td style=\"text-align:right;\"> 0.6839771 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> bus_stop_count </td>\n   <td style=\"text-align:right;\"> 1.182918 </td>\n   <td style=\"text-align:right;\"> 1.152352 </td>\n   <td style=\"text-align:right;\"> 1.219617 </td>\n   <td style=\"text-align:right;\"> 1.087621 </td>\n   <td style=\"text-align:right;\"> 0.8453668 </td>\n   <td style=\"text-align:right;\"> 0.8199293 </td>\n   <td style=\"text-align:right;\"> 0.8677903 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> pri_school_count </td>\n   <td style=\"text-align:right;\"> 1.356158 </td>\n   <td style=\"text-align:right;\"> 1.316602 </td>\n   <td style=\"text-align:right;\"> 1.400657 </td>\n   <td style=\"text-align:right;\"> 1.164542 </td>\n   <td style=\"text-align:right;\"> 0.7373771 </td>\n   <td style=\"text-align:right;\"> 0.7139509 </td>\n   <td style=\"text-align:right;\"> 0.7595310 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> flat_modelDBSS </td>\n   <td style=\"text-align:right;\"> 9.737887 </td>\n   <td style=\"text-align:right;\"> 9.296974 </td>\n   <td style=\"text-align:right;\"> 10.202230 </td>\n   <td style=\"text-align:right;\"> 3.120559 </td>\n   <td style=\"text-align:right;\"> 0.1026917 </td>\n   <td style=\"text-align:right;\"> 0.0980178 </td>\n   <td style=\"text-align:right;\"> 0.1075619 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> flat_modelImproved </td>\n   <td style=\"text-align:right;\"> 179.753156 </td>\n   <td style=\"text-align:right;\"> 171.186319 </td>\n   <td style=\"text-align:right;\"> 188.751231 </td>\n   <td style=\"text-align:right;\"> 13.407205 </td>\n   <td style=\"text-align:right;\"> 0.0055632 </td>\n   <td style=\"text-align:right;\"> 0.0052980 </td>\n   <td style=\"text-align:right;\"> 0.0058416 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> flat_modelModel.A </td>\n   <td style=\"text-align:right;\"> 226.806430 </td>\n   <td style=\"text-align:right;\"> 215.990677 </td>\n   <td style=\"text-align:right;\"> 238.166301 </td>\n   <td style=\"text-align:right;\"> 15.060094 </td>\n   <td style=\"text-align:right;\"> 0.0044090 </td>\n   <td style=\"text-align:right;\"> 0.0041987 </td>\n   <td style=\"text-align:right;\"> 0.0046298 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> flat_modelNew.Generation </td>\n   <td style=\"text-align:right;\"> 210.875295 </td>\n   <td style=\"text-align:right;\"> 200.820973 </td>\n   <td style=\"text-align:right;\"> 221.435517 </td>\n   <td style=\"text-align:right;\"> 14.521546 </td>\n   <td style=\"text-align:right;\"> 0.0047421 </td>\n   <td style=\"text-align:right;\"> 0.0045160 </td>\n   <td style=\"text-align:right;\"> 0.0049796 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> flat_modelPremium.Apartment </td>\n   <td style=\"text-align:right;\"> 25.122070 </td>\n   <td style=\"text-align:right;\"> 23.945849 </td>\n   <td style=\"text-align:right;\"> 26.358586 </td>\n   <td style=\"text-align:right;\"> 5.012192 </td>\n   <td style=\"text-align:right;\"> 0.0398056 </td>\n   <td style=\"text-align:right;\"> 0.0379383 </td>\n   <td style=\"text-align:right;\"> 0.0417609 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> flat_modelSimplified </td>\n   <td style=\"text-align:right;\"> 42.063068 </td>\n   <td style=\"text-align:right;\"> 40.077145 </td>\n   <td style=\"text-align:right;\"> 44.149917 </td>\n   <td style=\"text-align:right;\"> 6.485605 </td>\n   <td style=\"text-align:right;\"> 0.0237738 </td>\n   <td style=\"text-align:right;\"> 0.0226501 </td>\n   <td style=\"text-align:right;\"> 0.0249519 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> flat_modelStandard </td>\n   <td style=\"text-align:right;\"> 51.903915 </td>\n   <td style=\"text-align:right;\"> 49.447646 </td>\n   <td style=\"text-align:right;\"> 54.484714 </td>\n   <td style=\"text-align:right;\"> 7.204437 </td>\n   <td style=\"text-align:right;\"> 0.0192664 </td>\n   <td style=\"text-align:right;\"> 0.0183538 </td>\n   <td style=\"text-align:right;\"> 0.0202234 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Calibrate final model\n\nAs all the flat_model dummy columns have VIF \\> 10 except for DBSS model. We exclude all of these columns except for `flat_modelDBSS` and run the linear regression model again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_mlr <- lm(resale_price ~ floor_area_sqm +\n                  storey_order + remaining_lease_yrs +\n                  PROX_CBD + PROX_ELDERCARE + PROX_HAWKER +\n                  PROX_MRT + PROX_PARK + PROX_MALL + \n                  PROX_SUPERMARKETS + \n                  PROX_CLINIC + kindergarten_count +\n                  childcare_count + bus_stop_count +\n                  pri_school_count + flat_modelDBSS,\n                data=train_data)\n\nols_regress(price_mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              Model Summary                                \n--------------------------------------------------------------------------\nR                           0.872       RMSE                    43167.880 \nR-Squared                   0.761       MSE                1868464078.877 \nAdj. R-Squared              0.761       Coef. Var                  10.495 \nPred R-Squared              0.759       AIC                    153722.657 \nMAE                     31730.772       SBC                    153844.283 \n--------------------------------------------------------------------------\n RMSE: Root Mean Square Error \n MSE: Mean Square Error \n MAE: Mean Absolute Error \n AIC: Akaike Information Criteria \n SBC: Schwarz Bayesian Criteria \n\n                                     ANOVA                                      \n-------------------------------------------------------------------------------\n                    Sum of                                                     \n                   Squares          DF       Mean Square       F          Sig. \n-------------------------------------------------------------------------------\nRegression    3.775929e+13          16      2.359955e+12    1263.046    0.0000 \nResidual      1.184233e+13        6338    1868464078.877                       \nTotal         4.960161e+13        6354                                         \n-------------------------------------------------------------------------------\n\n                                              Parameter Estimates                                                \n----------------------------------------------------------------------------------------------------------------\n              model           Beta    Std. Error    Std. Beta       t        Sig           lower          upper \n----------------------------------------------------------------------------------------------------------------\n        (Intercept)    -121041.257      7409.850                 -16.335    0.000    -135567.070    -106515.444 \n     floor_area_sqm       5437.384        97.777        0.349     55.610    0.000       5245.708       5629.060 \n       storey_order       3449.951       109.341        0.214     31.552    0.000       3235.606       3664.297 \nremaining_lease_yrs       3922.757        42.365        0.743     92.594    0.000       3839.707       4005.807 \n           PROX_CBD      -8488.633       168.762       -0.429    -50.299    0.000      -8819.464      -8157.802 \n     PROX_ELDERCARE      -2750.815      1108.676       -0.017     -2.481    0.013      -4924.196       -577.435 \n        PROX_HAWKER      -6236.707      1526.420       -0.029     -4.086    0.000      -9229.007      -3244.407 \n           PROX_MRT     -35599.234      1759.413       -0.137    -20.234    0.000     -39048.279     -32150.188 \n          PROX_PARK     -13741.182      1660.426       -0.057     -8.276    0.000     -16996.178     -10486.186 \n          PROX_MALL     -12048.548      1661.539       -0.050     -7.251    0.000     -15305.727      -8791.369 \n  PROX_SUPERMARKETS       6753.333      3441.431        0.015      1.962    0.050          6.963      13499.702 \n        PROX_CLINIC      52619.006      5114.583        0.075     10.288    0.000      42592.693      62645.319 \n kindergarten_count       8072.823       732.305        0.081     11.024    0.000       6637.257       9508.388 \n    childcare_count      -2409.540       334.087       -0.054     -7.212    0.000      -3064.463      -1754.616 \n     bus_stop_count        930.380       221.226        0.028      4.206    0.000        496.703       1364.057 \n   pri_school_count       -408.141       437.272       -0.007     -0.933    0.351      -1265.343        449.060 \n     flat_modelDBSS      73540.327      5973.472        0.077     12.311    0.000      61830.301      85250.353 \n----------------------------------------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nThe result shows that `pri_school_count` has insignificant p-value of 0.351. We exclude this variable from the predictors and calibrate the model again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_mlr <- lm(resale_price ~ floor_area_sqm +\n                  storey_order + remaining_lease_yrs +\n                  PROX_CBD + PROX_ELDERCARE + PROX_HAWKER +\n                  PROX_MRT + PROX_PARK + PROX_MALL + \n                  PROX_SUPERMARKETS + \n                  PROX_CLINIC + kindergarten_count +\n                  childcare_count + bus_stop_count +\n                  flat_modelDBSS,\n                data=train_data)\n\nols_regress(price_mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              Model Summary                                \n--------------------------------------------------------------------------\nR                           0.872       RMSE                    43170.846 \nR-Squared                   0.761       MSE                1868426113.617 \nAdj. R-Squared              0.761       Coef. Var                  10.495 \nPred R-Squared              0.759       AIC                    153721.531 \nMAE                     31715.584       SBC                    153836.400 \n--------------------------------------------------------------------------\n RMSE: Root Mean Square Error \n MSE: Mean Square Error \n MAE: Mean Absolute Error \n AIC: Akaike Information Criteria \n SBC: Schwarz Bayesian Criteria \n\n                                     ANOVA                                      \n-------------------------------------------------------------------------------\n                    Sum of                                                     \n                   Squares          DF       Mean Square       F          Sig. \n-------------------------------------------------------------------------------\nRegression    3.775766e+13          15      2.517177e+12    1347.218    0.0000 \nResidual      1.184395e+13        6339    1868426113.617                       \nTotal         4.960161e+13        6354                                         \n-------------------------------------------------------------------------------\n\n                                              Parameter Estimates                                                \n----------------------------------------------------------------------------------------------------------------\n              model           Beta    Std. Error    Std. Beta       t        Sig           lower          upper \n----------------------------------------------------------------------------------------------------------------\n        (Intercept)    -121560.205      7388.887                 -16.452    0.000    -136044.922    -107075.488 \n     floor_area_sqm       5432.111        97.613        0.348     55.650    0.000       5240.757       5623.464 \n       storey_order       3454.012       109.253        0.214     31.615    0.000       3239.839       3668.186 \nremaining_lease_yrs       3923.891        42.347        0.743     92.660    0.000       3840.877       4006.906 \n           PROX_CBD      -8532.163       162.189       -0.431    -52.606    0.000      -8850.107      -8214.218 \n     PROX_ELDERCARE      -2571.665      1091.924       -0.016     -2.355    0.019      -4712.206       -431.124 \n        PROX_HAWKER      -6336.132      1522.683       -0.030     -4.161    0.000      -9321.106      -3351.157 \n           PROX_MRT     -35287.557      1727.417       -0.136    -20.428    0.000     -38673.880     -31901.235 \n          PROX_PARK     -13907.886      1650.775       -0.058     -8.425    0.000     -17143.964     -10671.808 \n          PROX_MALL     -11929.625      1656.630       -0.049     -7.201    0.000     -15177.181      -8682.070 \n  PROX_SUPERMARKETS       7107.188      3420.451        0.016      2.078    0.038        401.948      13812.429 \n        PROX_CLINIC      52372.010      5107.681        0.074     10.254    0.000      42359.228      62384.792 \n kindergarten_count       8071.060       732.295        0.081     11.022    0.000       6635.514       9506.606 \n    childcare_count      -2443.520       332.094       -0.055     -7.358    0.000      -3094.537      -1792.503 \n     bus_stop_count        931.647       221.219        0.028      4.211    0.000        497.982       1365.312 \n     flat_modelDBSS      73453.453      5972.686        0.077     12.298    0.000      61744.967      85161.938 \n----------------------------------------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nNow all the parameters are statistically significant. Key observations of the model output are as following:\n\n-   **Positive Predictors**:\n\n    -   `floor_area_sqm`, `storey_order`, and `remaining_lease_yrs` have positive coefficients, indicating that resale prices are likely to increase with larger floor area, higher floors, and longer remaining lease periods.\n\n    -   Certain amenities proximity, such as `PROX_SUPERMARKETS`, `PROX_CLINIC`, and the counts of kindergartens and bus stops also show a positive influence on price.\n\n-   **Negative Predictors**:\n\n    -   Interestingly, amenities proximity such as `PROX_CBD`, `PROX_ELDERCARE`, `PROX_HAWKER`, `PROX_MRT`, `PROX_PARK`, and `PROX_MALL` and higher `childcare_count` shows a negative coefficient. This suggests that being closer to these amenities may be associated with lower resale prices.\n\nWe write the model result to rds file for future use.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(price_mlr, \"data/rds/price_mlr.rds\" ) \n```\n:::\n\n\nNext we calculate the accuracy on `test_data` using below code chunk with the following functions:\n\n-   `predict()`: use `price_mlr` model to predict `resale_price` on `test_data`. The result is saved in column `lm_resale_price` in `test_data` sf dataframe.\n\n-   `mae()`: function from Metrics package to calculate the mean absolute error given the actual and predicted values.\n\n-   `rmse()`: function from Metrics package to calculate the root mean square error given the actual and predicted values.\n\n-   `cat()`: concatenate the text strings and print the result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make predictions on test data\ntest_data$lm_resale_price <- predict(price_mlr, newdata = test_data)\n# Calculate RMSE and MAE\nlm_rmse = rmse(test_data$resale_price, test_data$lm_resale_price)\nlm_mae = mae(test_data$resale_price, test_data$lm_resale_price)\n# Display accuracy metrics\ncat(\"Mean Absolute Error (MAE):\", lm_mae, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Absolute Error (MAE): 45175.31 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Root Mean Squared Error (RMSE):\", lm_rmse, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRoot Mean Squared Error (RMSE): 60416.34 \n```\n\n\n:::\n:::\n\n\nThe MAE is 45175.31 and RMSE is 60416.34 when using `price_mlr` linear regression model to predict `resale_price` on `test_data`, without taking into account geospatial location of the HDB block.\n\n# Non-spatial Random Forest\n\n## Prepare Coordinates data\n\nThe code chunk below extracts the x,y coordinates of the full, training and testing data sets. The result are saved in `coords_hdb`, `coords_train` and `coords_test` respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords_hdb <- st_coordinates(resale)\ncoords_train <- st_coordinates(train_data)\ncoords_test <- st_coordinates(test_data)\n```\n:::\n\n\nWe write all the output into rds file for future use.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(coords_hdb, \"data/rds/coords_hdb.rds\" )\nwrite_rds(coords_train, \"data/rds/coords_train.rds\" )\nwrite_rds(coords_test, \"data/rds/coords_test.rds\" )\n```\n:::\n\n\nAs random forest modelling function require aspatial dataframe, we drop the geometry from the train and test dataset using `st_drop_geometry()`. The output is saved in `train_data_nogeo` and `test_data_nogeo`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data_nogeo = train_data |> \n  st_drop_geometry()\ntest_data_nogeo = test_data |>\n  st_drop_geometry()\n```\n:::\n\n\n## Calibrate Random Forest Model\n\nIn this section, we explore how to calibrate a model to predict HDB resale price using random forest function of **ranger** package.\n\nBefore running the model, we set the seed using `set.seed()` to ensure the model result is reproducible. Next we use `ranger()` function to calibrate the random forest model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nrf <- ranger(resale_price ~ floor_area_sqm +\n                  storey_order + remaining_lease_yrs +\n                  PROX_CBD + PROX_ELDERCARE + PROX_HAWKER +\n                  PROX_MRT + PROX_PARK + PROX_MALL + \n                  PROX_SUPERMARKETS + PROX_TOP_SCHOOL +\n                  PROX_CLINIC + kindergarten_count +\n                  childcare_count + bus_stop_count +\n                  pri_school_count + flat_modelDBSS +\n                  flat_modelImproved + flat_modelModel.A +\n                  flat_modelNew.Generation + flat_modelPremium.Apartment +\n                  flat_modelSimplified + flat_modelStandard,\n             data=train_data_nogeo)\nrf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRanger result\n\nCall:\n ranger(resale_price ~ floor_area_sqm + storey_order + remaining_lease_yrs +      PROX_CBD + PROX_ELDERCARE + PROX_HAWKER + PROX_MRT + PROX_PARK +      PROX_MALL + PROX_SUPERMARKETS + PROX_TOP_SCHOOL + PROX_CLINIC +      kindergarten_count + childcare_count + bus_stop_count + pri_school_count +      flat_modelDBSS + flat_modelImproved + flat_modelModel.A +      flat_modelNew.Generation + flat_modelPremium.Apartment +      flat_modelSimplified + flat_modelStandard, data = train_data_nogeo) \n\nType:                             Regression \nNumber of trees:                  500 \nSample size:                      6355 \nNumber of independent variables:  23 \nMtry:                             4 \nTarget node size:                 5 \nVariable importance mode:         none \nSplitrule:                        variance \nOOB prediction error (MSE):       596759960 \nR squared (OOB):                  0.9235546 \n```\n\n\n:::\n:::\n\n\nThe model use the defaul number of trees of 500 to derive the forest using `train_data_nogeo`. We write the output to rds file using the below code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(rf, \"data/rds/rf.rds\")\n```\n:::\n\n\nNext we calculate the accuracy on `test_data_nogeo` using below code chunk with the following functions:\n\n-   `predict()`: use `rf` model to predict `resale_price` on `test_data_nogeo`. The result is saved in column `rf_resale_price` in `test_data_nogeo` dataframe.\n\n-   `mae()`: function from Metrics package to calculate the mean absolute error given the actual and predicted values.\n\n-   `rmse()`: function from Metrics package to calculate the root mean square error given the actual and predicted values.\n\n-   `cat()`: concatenate the text strings and print the result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make predictions on test_data\ntest_data_nogeo$rf_resale_price <- predict(rf, data = test_data_nogeo)$predictions\n\n# Calculate RMSE and MAE\nrf_rmse = rmse(test_data_nogeo$resale_price,\n               test_data_nogeo$rf_resale_price)\nrf_mae = mae(test_data_nogeo$resale_price, \n             test_data_nogeo$rf_resale_price)\n# Display accuracy metrics\ncat(\"Mean Absolute Error (MAE):\", rf_mae, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Absolute Error (MAE): 36615.87 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Root Mean Squared Error (RMSE):\", rf_rmse, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRoot Mean Squared Error (RMSE): 49840.55 \n```\n\n\n:::\n:::\n\n\nThe non-spatial Random Forest model have a lower MAE and RMSE than the previous multiple linear regression model, which indicate this random forest model performs better at predicting `resale_price` given the same set of predictors.\n\n# Geographically Weighted Random Forest (GWRF)\n\nIn this section, we explore how to calibrate a model to predict HDB resale price using `grf()` function of **SpatialML** package.\n\nKey arguments used in below function:\n\n-   `formula`: indicate the model dependent and independent variables\n\n-   `dframe`: a non-spatial data frame of the data to be used for training\n\n-   `bw`: the number of nearest neighbors to be considered\n\n-   `kernel`: use `adaptive` kernel\n\n-   `coords`: load in the respective X and Y coordinates from `coords_train`\n\n-   `ntree`: number of trees to grow for each local forest, we use 500 trees as default.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ngwRF_adaptive <- grf(formula = resale_price ~ floor_area_sqm +\n                  storey_order + remaining_lease_yrs +\n                  PROX_CBD + PROX_ELDERCARE + PROX_HAWKER +\n                  PROX_MRT + PROX_PARK + PROX_MALL + \n                  PROX_SUPERMARKETS + PROX_TOP_SCHOOL +\n                  PROX_CLINIC + kindergarten_count +\n                  childcare_count + bus_stop_count +\n                  pri_school_count + flat_modelDBSS +\n                  flat_modelImproved + flat_modelModel.A +\n                  flat_modelNew.Generation + flat_modelPremium.Apartment +\n                  flat_modelSimplified + flat_modelStandard,\n                     dframe=train_data_nogeo, \n                     bw=55,\n                     kernel=\"adaptive\",\n                     coords=coords_train,\n                  ntree=500)\n```\n:::\n\n\nThe model output is saved into rds format using the below code chunk for future use and avoid having to run the model again, as calibrating GWRF takes long time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(gwRF_adaptive, \"data/rds/gwRF_adaptive.rds\")\n```\n:::\n\n\nThe below code chunk retrieves the saved model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwRF_adaptive <- read_rds(\"data/rds/gwRF_adaptive.rds\")\n```\n:::\n\n\n## Predict using test data\n\nThe code chunk below combines the test data with its corresponding coordinates data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data_nogeom <- cbind(\n  test_data_nogeo, coords_test)\n```\n:::\n\n\nNext, `predict.grf()` of **spatialML** package is used to predict the resale price using the test data and gwRF_adaptive model calibrated earlier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwRF_pred <- predict.grf(gwRF_adaptive, \n                           test_data_nogeom, \n                           x.var.name=\"X\",\n                           y.var.name=\"Y\", \n                           local.w=1,\n                           global.w=0)\n```\n:::\n\n\nBefore moving on, we save the output into rds file for future usage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(gwRF_pred, \"data/rds/GRF_pred.rds\")\n```\n:::\n\n\n### Convert the predicting output into a data frame\n\nThe output of the `predict.grf()` is a vector of predicted values. It is more efficient to convert it into a data frame for further visualization and analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGRF_pred <- read_rds(\"data/rds/GRF_pred.rds\")\nGRF_pred_df <- as.data.frame(GRF_pred)\n```\n:::\n\n\nNext `cbind()` is used to append the predicted values onto `test_data`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data_p <- cbind(test_data, GRF_pred_df)\n```\n:::\n\n\nWe write the result to rds file format using below code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(test_data_p, \"data/rds/test_data_p.rds\")\n```\n:::\n\n\nThe below code chunk calculates and print out the RMSE and MAE of predicted resale price on test data using the above `gwRF_adaptive` model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrf_rmse = rmse(test_data_p$resale_price, test_data_p$GRF_pred)\ngrf_mae = mae(test_data_p$resale_price, test_data_p$GRF_pred)\n# Display accuracy metrics\ncat(\"Mean Absolute Error (MAE):\", grf_mae, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Absolute Error (MAE): 41845.79 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Root Mean Squared Error (RMSE):\", grf_rmse, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRoot Mean Squared Error (RMSE): 70708.71 \n```\n\n\n:::\n:::\n\n\n# Compare Model Performance\n\n## RMSE and MAE\n\nRoot Mean Squared Error (RMSE) and Mean Absolute Error (MAE) are commonly used metrics to evaluate and compare model performance on test data. RMSE measures the square root of the average squared differences between predicted and actual values, penalizing larger errors more heavily, while MAE calculates the average absolute differences, providing a more straightforward interpretation of the average error magnitude. When comparing linear regression and random forest models, lower RMSE and MAE values indicate better predictive accuracy. If the random forest model yields lower RMSE and MAE values than linear regression, it suggests that the random forest captures complex, non-linear relationships in the data more effectively. However, if linear regression performs similarly, it may indicate that a simpler, interpretable model is sufficient for the task.\n\nThe below code chunk prints out the RMSE and MAE of the 3 predictive models we have calibrated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Non-spatial Linear Regression - MAE:\", lm_mae, \"RMSE:\", lm_rmse, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNon-spatial Linear Regression - MAE: 45175.31 RMSE: 60416.34 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Non-spatial Random Forest - MAE:\", rf_mae, \"RMSE:\", rf_rmse, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNon-spatial Random Forest - MAE: 36615.87 RMSE: 49840.55 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Geographically Weighted Random Forest - MAE:\", grf_mae, \"RMSE:\", grf_rmse, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeographically Weighted Random Forest - MAE: 41845.79 RMSE: 70708.71 \n```\n\n\n:::\n:::\n\n\nThe output shows that:\n\n-   Non-spatial Random Forest has the best performance on `test_data` with the lowest MAE and RMSE.\n\n-   Geographically weighted Random Forest has the second lowest MAE but has the highest RMSE, indicating large errors on certain records.\n\n-   Linear Regression has the highest MAE and second highest RMSE, suggesting the relationship between resale price and other predictors are likely non-linear, which is better captured in Random Forest model.\n\n-   GWRF’s lower performance compared to non-spatial Random Forest may result from overfitting due to spatial non-stationarity. Calculating an optimal adaptive bandwidth could improve this, though attempts to use the `grf.bw()` function were unsuccessful, as it is still in development (as stated in [SpatialML documents](https://cran.r-project.org/web/packages/SpatialML/SpatialML.pdf)). We can try again when further improvement of this function is included in future version of SpatialML package.\n\n## Visualize the Predicted Values\n\nUsing a scatterplot to visualize actual versus predicted resale prices on the test dataset offers a clear, intuitive way to assess model performance. By plotting actual prices on one axis and predicted prices on the other, we can quickly see how well the model aligns with real values. Ideally, the points should fall along a 45-degree line, indicating that predictions closely match actual outcomes. Deviations from this line reveal errors and can highlight patterns, such as systematic under- or over-predictions. Additionally, scatterplots can help identify any potential outliers or segments where the model performs poorly, providing valuable insights for model refinement.\n\nThe below code chunk uses `ggplot` function to create 3 scatterplots on actual resale prices and predicted resale prices of the 3 models derived. The output plot are saved in `plot_lm`, `plot_rf` and `plot_grf`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression scatter plot\nplot_lm = ggplot(data = test_data,\n       aes(x = resale_price,\n           y = lm_resale_price)) +\n   geom_point(alpha = 0.5) +\n  geom_abline(slope = 1, intercept = 0, color = \"red\", linetype = \"dashed\") +\n  labs(x = \"Actual Resale Price\", \n       y = \"Predicted Resale Price (Linear Regression)\", \n       title = \"MLR\") +\n  theme_minimal()\n# Random forrest scatter plot\nplot_rf = ggplot(data = test_data_nogeo,\n       aes(x = resale_price,\n           y = rf_resale_price)) +\n  geom_point(alpha = 0.5) +\n  geom_abline(slope = 1, intercept = 0, color = \"red\", linetype = \"dashed\") +\n  labs(x = \"Actual Resale Price\", \n       y = \"Predicted Resale Price (Random Forest)\", \n       title = \"RF\") +\n  theme_minimal()\n# GWRF scatter plot\nplot_grf = ggplot(data = test_data_p,\n       aes(x = resale_price,\n           y = GRF_pred)) +\n  geom_point(alpha = 0.5) +\n  geom_abline(slope = 1, intercept = 0, color = \"red\", linetype = \"dashed\") +\n  labs(x = \"Actual Resale Price\", \n       y = \"Predicted Resale Price (GWRF)\", \n       title = \"GWRF\") +\n  theme_minimal()\n```\n:::\n\n\nThe below code chunk use `grid.arrange()` function from **gridExtra** package to draw the 3 scatter plots on the same row for easier comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngridExtra::grid.arrange(plot_lm, plot_rf, plot_grf, nrow = 1)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-88-1.png){width=672}\n:::\n:::\n\n\nThe scatter plots of all three models show most points falling below the diagonal, indicating a tendency to underpredict resale prices, especially as prices increase. In the GWRF model, some of the points deviate significantly from the diagonal line, explaining why its RMSE is significantly higher compared to the other models. This supports the earlier observation of potential overfitting in the GWRF model, and calculating the optimal adaptive bandwidth could help improve its performance.\n\n# Conclusion\n\nIn summary, the predictive modeling of HDB resale prices using three approaches—Linear Regression, Random Forest, and Geographically Weighted Random Forest (GWRF)—has provided insights into the strengths and limitations of each model. The non-spatial Random Forest model achieved the best performance, with the lowest Mean Absolute Error (MAE) and Root Mean Square Error (RMSE) on the test dataset, indicating its effectiveness in capturing non-linear relationships between resale prices and the predictors. The Linear Regression model had the weakest performance, suggesting that a linear model does not adequately capture the complexity of the factors influencing resale prices. Although the GWRF model achieved a lower MAE than Linear Regression, it had the highest RMSE, showing that it struggles with larger errors on certain records, potentially due to spatial overfitting.\n\nThe scatter plots further reinforce these findings, showing a consistent tendency across all models to underpredict higher resale prices. The GWRF model, in particular, exhibited significant deviations from the diagonal line, suggesting potential overfitting to local spatial patterns. This may be attributed to spatial non-stationarity, where the relationship between predictors and resale prices varies across locations. Refining the GWRF model with an optimal adaptive bandwidth could potentially address this issue and improve its accuracy; however, attempts to optimize the bandwidth with the `grf.bw()` function were unsuccessful, as the function took forever to load and can be due to it is still under development in the SpatialML package.\n",
    "supporting": [
      "Take-home_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}