project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "1.1 - Geospatial Data Wrangling with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex011.html"
        - text: "1.2 - Choropleth Mapping with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex012.html"
        - text: "2.1 - 1st Order Spatial Point Patterns Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex021.html"
        - text: "2.2 - 2nd Order Spatial Point Patterns Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex022.html"
        - text: "3.1 - Network Constrained Spatial Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex031.html"
        - text: "4.1 - Spatial Weights and Applications"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex041.html"
        - text: "5.1 - Global Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex051.html"
        - text: "5.2 - Local Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex052.html"
        - text: "6.1 - Geographical Segmentation with Spatially Constrained Clustering Techniques"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex061.html"
        - text: "7.1 - Calibrate Hedonic Pricing Model for Private Highrise Property"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "8.1 - Geographically Weighted Predictive Models"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "9.1 - Modelling Geographical Accessibility"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
        - text: "10.1 - Process and Visualize Flow Data"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex101.html"
        - text: "10.2 - Calibrate Spatial Interaction Models with R"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex102.html"
      - text: "In-class Exercise"
        menu: 
        - text: "1 - Geospatial Data Analysis with R"
          href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
        - text: "2 - Spatial Point Pattern Analysis"
          href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
        - text: "3 - Network Constrained Spatial Point Patterns Analysis"
          href: In-class_Ex/In-class_Ex03/In-class_Ex03.html
        - text: "4 - Geographically Weighted Summary Statistics"
          href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
        - text: "5 - Global and Local Measures of Spatial Autocorrelation"
          href: In-class_Ex/In-class_Ex05/In-class_Ex05.html
        - text: "6 - Emerging Hot Spot Analysis (EHSA)"
          href: In-class_Ex/In-class_Ex06/In-class_Ex06.html
        - text: "7 - Calibrate Hedonic Pricing Model for Private Highrise Property"
          href: In-class_Ex/In-class_Ex07/In-class_Ex07.html
        - text: "8 - Geographically Weighted Predictive Models"
          href: In-class_Ex/In-class_Ex08/In-class_Ex08.html
      - text: "Take-home Exercise"
        menu: 
        - text: "1 - Geospatial Analytics for Public Good"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "2 - Discovering impacts of COVID-19 on Thailand tourism economy using spatial and spatio-temporal statistics"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - text: "{{< iconify fa6-brands linkedin size=2xl >}}"
        href: 'https://www.linkedin.com/in/nguyenbaothuphuong/'

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    number-sections: true
    code-copy: true

editor: visual

