project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "1.1 - Geospatial Data Wrangling with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex011.html"
        - text: "1.2 - Choropleth Mapping with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex012.html"
        - text: "2.1 - 1st Order Spatial Point Patterns Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex021.html"
        - text: "2.2 - 2nd Order Spatial Point Patterns Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex022.html"
      - text: "In-class Exercise"
        menu: 
        - text: "1 - Geospatial Data Analysis with R"
          href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
        - text: "2 - Spatial Point Pattern Analysis"
          href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
      - text: "Take-home Exercise"
        menu: 
        - text: "1 - Thailand Road Accidents Analysis"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - text: "{{< iconify fa6-brands linkedin size=2xl >}}"
        href: 'https://www.linkedin.com/in/nguyenbaothuphuong/'

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    number-sections: true
    code-copy: true

editor: visual

